### ISSUE TITLE
"pkgin: could not fetch packages" error 

### ISSUE THREAD

**Issue by lupa18** [RedCoolBeans/CargOS#1]
CargOS Version: 2016.1

Hello, I had installed this version and trying to install openssh and wget but problem fetching packages appear all time.

**Comment by reinerj** [comment]
Hi,

openssh is installed by default. So there is no need to install it manually. 

Can you please explain what exactly you are trying to do? Do you want login over ssh with password as root maybe? this is disabled by default. you have to add a ssh key or to allow it in the sshd config. 

Regards
Reiner

**Comment by lupa18** [comment]
Sorry, but I couldn't find openssh: 
1. Nothing in /bin nor /usr/bin
2. Nothing in /etc/openssh nor /etc/defaults

Anyway... maybe I will need wget but can't use pkgin

**Comment by reinerj** [comment]
Hi,

I assume you are looking for the sshd config. This file is located in /usr/pkg/etc/ssh/

More information how to use or install packages you can found in the Wiki:
https://github.com/RedCoolBeans/CargOS/wiki/Using-packages

Regards
Reiner

**Comment by lupa18** [comment]
Ok. It's there. Thanks ! 

I still having the connection problem: 

![cargos01](https://cloud.githubusercontent.com/assets/463429/12794283/11f309fc-ca93-11e5-8ca1-1aaad41eaf03.png)

**Comment by rnagy** [comment]
Hi

This is clearly a networking issue as you cannot reach the download.cargos.io site from your network. The package manager does a simple http request to get a file but you can neither connect to the server nor send icmp packets to it.
If you can give us your IP address we can also contact our ISP to investigate the issue.

Thank you!

**Comment by lupa18** [comment]
Yes, I have a complex network configuraton, but it's weird that ping to google works and to other sites too, but not to download.cargos.io .. my IP:195.154.200.92 / ISP: online.net

**Comment by rnagy** [comment]
The issue is not on our side of the network, we can reach through to 195.154.1.65, after that I can't see what's going on. Please investigate in your network as well.

> traceroute to 195.154.200.92 (195.154.200.92), 64 hops max, 40 byte packets
> 1  84.2.34.129  0.42 ms  0.356 ms  0.3 ms
> 2  194.38.107.226  0.706 ms  0.59 ms  0.709 ms
> 3  81.183.2.207  0.53 ms 81.183.2.205  0.463 ms  0.572 ms
> 4  81.183.0.242  0.727 ms 81.183.0.196  0.892 ms 81.183.0.69  0.731 ms
> 5  81.183.0.59  0.877 ms 81.183.1.116  1.044 ms 81.183.1.118  1.047 ms
> 6  213.248.73.101  24.869 ms 62.115.14.1  21.409 ms 213.248.73.101  27.217 ms
> 7  80.91.250.163  21.554 ms 62.115.143.116  18.517 ms 80.91.250.163  21.537 ms
> 8  62.115.135.10  100.619 ms 62.115.139.229  24.763 ms 62.115.113.136  28.518 ms
> 9  62.115.112.122  31.829 ms  31.831 ms 62.115.140.35  30.623 ms
> 10  213.155.134.227  29.931 ms 213.155.134.231  27.821 ms 213.155.132.199  27.832 
> 11  62.115.40.78  29.424 ms  29.163 ms  29.401 ms
> 12  195.154.1.65  30.63 ms  32.578 ms  32.31 ms
> 13  \* \* *
> 14  \* \* *
> 15  \* \* *
> 16  \* \* *
> 17  \* \* *

**Comment by lupa18** [comment]
I don't know how but it's solved. But was our problem.
