### ISSUE TITLE
sudo password bypass

### ISSUE THREAD

**Issue by lupa18** [RedCoolBeans/CargOS#2]
Hello !!
Cargos version: 2016.3
sudo: sudo-1.7.10p9

When I set a password or more, only first 7 characters are parsed, so if I set: comeon123456 these will work: 
- comeon1234
- comeon12rerer
- comeon12222
- etc..

**Comment by reinerj** [comment]
This is a bug in busybox. We are working on it. With the new release the problem should be fixed. 

Thanks

**Comment by reinerj** [comment]
2016.04 will fix the problem reported. You have to change your password then that the hashing will be used. 

I will close this ticket now
