### ISSUE TITLE
Problems upgradig to 2016.4

### ISSUE THREAD

**Issue by lupa18** [RedCoolBeans/CargOS#3]
I did: 
`sudo cargos-upgrade`

then I had to install grub but It said that I need install grub2, so:

```
sudo pkgin in grub2                                                                              [11/11]
Password:
pkgin: /usr/pkg/etc/pkgin/repositories.conf has no repositories or does not exist.
```

Then I added CargOS repos to /usr/pkg/etc/pkgin/repositories.conf (because was misconfigured)

Finally I got grub2 installed and upgrade command executed, but with this error: 
`CargOS is not configured to boot from disk(s)`

Finally I rebooted and CargOS doesn't upgrade: 

```
cat /etc/cargos-release 
2016.03
```

How can I achieve this?

**Comment by rnagy** [comment]
Hi!

Are you booting your current 2016.03 installation from disk?

**Comment by lupa18** [comment]
Hello, thanks for your question. Yes, from a virtualdisk over quemu-kvm

**Comment by rnagy** [comment]
There was a bug up until 2016.04 which may have caused the boot from disk support
to break, so in order to fix this, you will have to manually update to 2016.04 and from
there you can use the script again.

First please mount your /boot directory by issuing mount /dev/{s,v}da1 /boot.
Then please download the required files into /boot

http://download.cargos.io/2016.04/x86_64/bzImage-2016.04

and

http://download.cargos.io/2016.04/x86_64/rootfs.squashfs-noinst-2016.04

Then edit /boot/grub/grub.cfg and add the following before your 2016.03 entries
so worst case you can still boot 2016.03.

menuentry 'CargOS-2016.04' {
    set background_color=black
    linux    /bzImage-2016.04 root=/dev/ram0 ramdisk_size=131072 quiet
    initrd   /rootfs.squashfs-noinst-2016.04
}
menuentry 'CargOS-2016.04 with serial console on ttyS0' {
    set background_color=black
    linux    /bzImage-2016.04 console=ttyS0 root=/dev/ram0 ramdisk_size=131072 quiet
    initrd   /rootfs.squashfs-noinst-2016.04
}

Then you can reboot and run cargos-upgrade -u.

**Comment by lupa18** [comment]
Thanks @rnagy ! only a queston, /boot folder must be created? because I don't have one :-/

**Comment by rnagy** [comment]
Well yes but you can't create it so please mount it to /mnt for example. Then 2016.04 will have /boot
created.

**Comment by lupa18** [comment]
Well, I mounted the /dev/vda1 into /mnt but it doesn't has a /boot folder. 

Then I tried to install grub there, doing: 
`grub-install /dev/vda1 --boot-directory=/mnt/boot/`

With bad results: 

```
/usr/pkg/share/grub/grub-mkconfig_lib: line 53: 22926 Killed                  "${grub_probe}" -t fs "$path" > /dev/null 2>&1
Path `/mnt/boot/grub' is not readable by GRUB on boot. Installation is impossible. Aborting.

```

Now boot/grub folder exists under /mnt

Doing something wrong?

**Comment by rnagy** [comment]
Well then initially you did not install CargOS to boot from disk. If you really want to boot
CargOS from your local disk, then please change your VM to boot an ISO of 2016.04,
then simply run cargos-upgrade and after that you have to run cargos-upgrade -f
to install CargOS and the boot loader to the disk itself.

**Comment by lupa18** [comment]
> Well then initially you did not install CargOS to boot from disk. 

I don't know why, because I follow all your steps :-/

So do you mean a fresh install, and I will migrate all my docker data and containers?

**Comment by rnagy** [comment]
No not at all. CargOS is designed mainly to run from memory without installing it to disk,
so even if you boot the ISO it will see that you have a configured system and not touch it.
Just boot the 2016.04 ISO and do the upgrade steps as I said that way you will update
your installation to 2016.04 and then you will install boot loader support from the disk
with cargos-upgrade.
You can boot CargOS from PXE, ISO without the need of having the cargos images on your disk,
but if someone wishes that, it's still possible with the 'install cargos to the disk' option, which
essentially will just download the cargos image and kernel to the /boot partition and install a boot loader.

**Comment by lupa18** [comment]
Ok. Thanks. Fixed !!
